task: erx

train:
  dataset:
    path: bdsaglam/web_nlg-erx-concat
    name: release_v3.0_en
    split: train[:100]
  optimizer: noop
  ensemble: no

evaluation:
  dataset:
    path: bdsaglam/web_nlg-erx-concat
    name: release_v3.0_en
    split: dev[:1000]

program:
  prompting: structured

lm:
  model: llama-3-8b
  temperature: 0.0

run: 1
